### PR TITLE
fix: send Portkey as user-agent

### LINKED ISSUE #634: [Provider] Cerebras not working with gateway
### What Happened?

Getting 403 when cerebras accessed through gateway.

### What Should Have Happened?

Request should go through and a positive response should be there.

### Relevant Code Snippet

_No response_

### Your Twitter/LinkedIn

_No response_

### PR DESCRIPTION
**Pull request by b4s36t4**
**Title:** 
Fix: Cerebras returning 401.

**Motivation:** (optional)
- Cerebras is not working with gateway.

Closes #634

### CODE REVIEW

File: src/handlers/retryHandler.ts [hunk 1]
```diff
@@ -72,7 +72,13 @@ export const retryRequest = async (
         try {
           const response: Response = timeout
             ? await fetchWithTimeout(url, options, timeout)
-            : await fetch(url, options);
+            : await fetch(url, {
+                ...options,
+                headers: {
+                  ...options.headers,
+                  'User-Agent': 'Portkey Gateway/1.0',
```
Comment (VisargD) [inline src/handlers/retryHandler.ts]: Hey! This should ideally be a part of the providers `headers` method.

**Review by narengogi — APPROVED** [review]

**Comment by narengogi** [comment]
Please create github issue for tracking

**Review by VisargD — APPROVED** [review]
