### PR TITLE
fix: custom host validator to protect from ssrf attack

### LINKED ISSUE #1359: Security Vulnerability Report
I am writing to inform you that an email regarding a security vulnerability has been sent from work.soohyun@gmail.com. I would be grateful if you could review it at your earliest convenience.

Thank you for your time and attention to this matter.

Best regards,
Kim soohyun

### PR DESCRIPTION
**Pull request by sk-portkey**
## Description
Validator to protect [SSRF](https://owasp.org/www-community/attacks/Server_Side_Request_Forgery) attacks

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring (no functional changes)

## How Has This Been Tested?

- [ ] Unit Tests
- [ ] Integration Tests
- [ ] Manual Testing

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/middlewares/requestValidator/index.ts [hunk 1]
```diff
@@ -153,3 +153,136 @@ export const requestValidator = (c: Context, next: any) => {
...
   return next();
 };
+
+function isValidCustomHost(customHost: string) {
+  try {
+    const value = customHost.trim().toLowerCase();
+
+    // Project-specific and obvious disallowed schemes/hosts
+    if (value.indexOf('api.portkey') > -1) return false;
+    if (value.startsWith('file://')) return false;
```
Comment (narengogi) [inline src/middlewares/requestValidator/index.ts]: ln number 162:165 and ln:171 do the same thing (check for protocol), so this is redundant

File: src/middlewares/requestValidator/index.ts [hunk 2]
```diff
@@ -153,3 +153,136 @@ export const requestValidator = (c: Context, next: any) => {
...
+
+    // Disallow credentials and obfuscation
+    if (url.username || url.password) return false;
+    if (customHost.includes('@')) return false;
+
+    const host = url.hostname.toLowerCase();
+
+    // Lenient allowance for local development
+    const localAllow =
+      host === 'localhost' ||
```
Comment (narengogi) [inline src/middlewares/requestValidator/index.ts]: {suggestion} would be good to have allowed domains configurable through an env variable

Comment (sk-portkey) [reply src/middlewares/requestValidator/index.ts]: done

- `ALLOWED_CUSTOM_HOSTS` - Comma-separated list of allowed custom host domains/IPs for the `x-portkey-custom-host` header. 
  - Format: `"localhost,127.0.0.1,example.com,my-internal-api.local"`
  - Default (if not set): `localhost,127.0.0.1,::1,host.docker.internal`
  - Used to whitelist trusted domains that can be called via custom host header
  - When `localhost` is in the list, `*.localhost` subdomains are also allowed

**Comment by sk-portkey** [comment]
Supports customisable environment variable:
- `TRUSTED_CUSTOM_HOSTS` - Comma-separated list of allowed custom host domains/IPs for the `x-portkey-custom-host` header.
  - `Format`: "localhost,127.0.0.1,example.com,my-internal-api.local"
  - `Default (if not set)`: localhost,127.0.0.1,::1,host.docker.internal
  - Used to whitelist trusted domains that can be called via custom host header
  - When localhost is in the list, *.localhost subdomains are also allowed

**Comment by narengogi** [comment]
tagging @im-soohyun for review

**Review by narengogi — COMMENTED** [review]
looks good, but would be nice to combine the multiple checks into a regex to shave off some μs ⚡️

**Review by narengogi — DISMISSED** [review]

**Review by im-soohyun — APPROVED** [review]

**Comment by im-soohyun** [comment]
@narengogi lgtm!!

**Comment by im-soohyun** [comment]
@narengogi 

Could you please create a security advisory for this on GitHub? I would appreciate being credited for finding it.

**Comment by sk-portkey** [comment]
hey @im-soohyun thanks a lot for finding the issue. we will create a security advisory and will definitely credit you

cc @VisargD @roh26it

**Comment by im-soohyun** [comment]
@sk-portkey 

thank you

**Comment by im-soohyun** [comment]
@sk-portkey 

Would it be possible to get a CVE issued for this security vulnerability?

**Review by VisargD — APPROVED** [review]
