### PR TITLE
fix: add role 'assistant' to chat completion stream chunk

### LINKED ISSUE #1399: fix: add role 'assistant' to chat completion stream chunk for anthropic provider

### PR DESCRIPTION
**Pull request by siddharthsambharia-portkey**
## Description
add role 'assistant' to chat completion stream chunk for Librechat support

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring (no functional changes)

## How Has This Been Tested?

- [x] Unit Tests
- [ ] Integration Tests
- [x] Manual Testing

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Related Issues
Fixed and closes #1399

### CODE REVIEW

File: src/providers/anthropic/chatComplete.ts [hunk 1]
```diff
@@ -771,6 +771,7 @@ export const AnthropicChatCompleteStreamChunkTransform: (
         {
           delta: {
             content,
+            role: 'assistant',
```
Comment (anatoliilitvinovr) [inline src/providers/anthropic/chatComplete.ts]: we might need move definition of role when `message_start` chunk is sent, as soon as that is only one place where role is streamed from Anthropic API and compatible with OpenAI streaming spec.

Comment (sambharia) [reply src/providers/anthropic/chatComplete.ts]: cc @b4s36t4 @narengogi

Comment (narengogi) [reply src/providers/anthropic/chatComplete.ts]: @anatoliilitvinovr valid but openai only sends role in the first chunk so this looks fine to me

Comment (narengogi) [reply src/providers/anthropic/chatComplete.ts]: and it's always assistant so might as well send for all chunks but this is fine

**Review by narengogi — DISMISSED** [review]

File: src/providers/anthropic/chatComplete.ts (hunk 1 above)
Comment (anatoliilitvinovr) [reply src/providers/anthropic/chatComplete.ts]: I see! I trust you guys, thank you, great job!

**Review by anatoliilitvinovr — APPROVED** [review]

File: src/providers/anthropic/chatComplete.ts
Comment (siddharthsambharia-portkey) [inline src/providers/anthropic/chatComplete.ts]: @narengogi  @b4s36t4 Should we add the role here?

**Review by b4s36t4 — APPROVED** [review]
